### PR TITLE
Send param as text instead of binary.

### LINKED ISSUE #221: Bail out when trying to bind a param for PQexecParams during be_pg_aclcheck
```
1490520171: New connection from 172.17.0.1 on port 1883.
1490520171: |-- mosquitto_auth_unpwd_check(7araVJ)
1490520171: |-- ** checking backend postgres
1490520171: |-- GETTING USERS: 7araVJ
1490520171: |-- getuser(7araVJ) AUTHENTICATED=1 by postgres
1490520171: New client connected from 172.17.0.1 as ESP8266-AirQuality (18fe34cf87cc) (c1, k60, u'7araVJ').
1490520171: Sending CONNACK to ESP8266-AirQuality (18fe34cf87cc) (0, 0)
1490520172: Received SUBSCRIBE from ESP8266-AirQuality (18fe34cf87cc)
1490520172: 	control/7araVJ (QoS 0)
1490520172: ESP8266-AirQuality (18fe34cf87cc) 0 control/7araVJ
1490520172: Sending SUBACK to ESP8266-AirQuality (18fe34cf87cc)
1490520172: Received SUBSCRIBE from ESP8266-AirQuality (18fe34cf87cc)
1490520172: 	control/ESP8266-AirQuality (QoS 0)
1490520172: ESP8266-AirQuality (18fe34cf87cc) 0 control/ESP8266-AirQuality
1490520172: Sending SUBACK to ESP8266-AirQuality (18fe34cf87cc)
1490520172: |-- mosquitto_auth_acl_check(..., ESP8266-AirQuality (18fe34cf87cc), 7araVJ, devices/7araVJ, MOSQ_ACL_WRITE)
1490520172: |-- SUPERUSER: 7araVJ
1490520172: |-- user is 0
1490520172: |-- USERNAME: 7araVJ, TOPIC: devices/7araVJ, acc: 2
ERROR:  incorrect binary data format in bind parameter 2

1490520172: |-- aclcheck(7araVJ, devices/7araVJ, 2) HAS_ERROR=Y by postgres
1490520172: |-- aclcheck(7araVJ, devices/7araVJ, 2) AUTHORIZED=0 by (null)
1490520172: |-- aclcheck(7araVJ, devices/7araVJ, 2) AUTHORIZED=N HAS_ERROR=Y => ERR_UNKNOWN
1490520172: Socket error on client ESP8266-AirQuality (18fe34cf87cc), disconnecting.
```

I could have sworn this has worked in the past.

While I find it difficult to understand why it breaks exactly, I've devised a fix. PR is on the way.

### PR DESCRIPTION
**Pull request by jasiek**
Closes #221.

### CODE REVIEW

File: be-postgres.c [hunk 1]
```diff
@@ -256,13 +256,15 @@ int be_pg_aclcheck(void *handle, const char *clientid, const char *username, con
 	if (!conf || !conf->aclquery)
 		return (FALSE);
 
-	int localacc = htonl(acc);
+	const int buflen = 11; // 10 for 2^32 + 1
+	char accbuffer[buflen];
+	memset(accbuffer, 0, buflen);
```
Comment (jpmens) [inline be-postgres.c]: this memset() is  not required

Comment (jasiek) [inline be-postgres.c]: Updated.

**Comment by jpmens** [comment]
Merged, thanks.
